- hosts: all
  become: no
  gather_facts: no
  tasks:
  - name: Run OLTP DB Sim
    script: oltpdb.sh  -x {{ xlargecpu }}  -l {{ largecpu }} -m {{ mediumcpu }} -s {{ smallcpu }} -i {{ iterations }}
    register: oltp
  - debug: msg="{{ oltp.stdout }}"