---
- hosts: all
  become: yes
  gather_facts: no

  tasks:
  - name: Update apt-cache
    apt: update_cache=yes
  - name: Install postgres
    apt: name={{item}}
    with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2

- hosts: all
  become: yes
  become_user: postgres
  gather_facts: no

  vars:
    dbuser: nutanix
    dbpassword: nutanix/4u

  tasks:
  - name: Create test database
    postgresql_db: name={{dbname}}

  - name: Ensure user has access to database
    postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

- hosts: all
  become: yes
  become_user: nutanix
  gather_facts: no

  tasks:
  - name: Prepare pgbench
    shell: pgbench --unlogged-tables -i -s {{pgbench_scale}} {{dbname}}
    register: pgbenchout
  - debug: msg="{{ pgbenchout.stdout }}"


