- hosts: all
  become: yes
  become_user: nutanix
  gather_facts: no

  tasks:
  - name: Run PGBench
    shell: pgbench -S -s {{pgbench_scale}} -c {{pgbench_clients}} -j {{pgbench_jobs}} -T {{pgbench_runtime}} {{dbname}}
    register: pgbenchout
  - debug: msg="{{ pgbenchout.stdout }}"
